import { ClerkProvider, currentUser } from "@clerk/nextjs";
import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { fetchUser } from "@/lib/actions/user.actions";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await currentUser();
  if (!user) return null;

  const userInfo = await fetchUser(user.id);

  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${inter.className} ${
            userInfo?.darkMode ? "bg-black text-white" : "bg-white"
          } transition-colors`}
        >
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
