import { ClerkProvider, currentUser } from '@clerk/nextjs';
import { fetchUser } from '@/lib/actions/user.actions';
import { Josefin_Sans } from 'next/font/google';
import Background from '@/components/Background';
import Header from '@/components/Header';
import { dark } from '@clerk/themes';
import type { Metadata } from 'next';
import '../globals.css';

const josefinSans = Josefin_Sans({
  subsets: ['latin'],
  weight: ['400', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await currentUser();
  if (!user) return null;

  const userInfo = await fetchUser(user.id);

  return (
    <ClerkProvider appearance={{ baseTheme: userInfo?.darkMode && dark }}>
      <html lang="en">
        <body
          className={`${josefinSans.className} ${
            userInfo?.darkMode
              ? 'bg-dark-700 text-white dark'
              : 'bg-light-100 text-light-500'
          } transition-colors relative`}
        >
          <main className="max-w-[592px] mx-auto px-[26px] w-full pb-24 md:pb-4">
            <Background isDarkMode={userInfo?.darkMode} />
            <Header currentDarkMode={userInfo?.darkMode} id={userInfo?.id} />
            {children}
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
