import { ClerkProvider } from '@clerk/nextjs';
import '../globals.css';
import type { Metadata } from 'next';
import { Josefin_Sans } from 'next/font/google';
import Background from '@/components/Background';

const josefinSans = Josefin_Sans({
  subsets: ['latin'],
  weight: ['400', '700'],
});

export const metadata: Metadata = {
  title: 'Login',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${josefinSans.className} min-h-[100svh] flex flex-col gap-10 items-center justify-center`}
        >
          <Background isDarkMode={false} />
          <h2 className="font-bold text-white md:text-[40px] md:tracking-[15.13px] text-[28px] tracking-[9.46px]">
            TODO
          </h2>
          <main className='px-[26px] w-full'>{children}</main>
        </body>
      </html>
    </ClerkProvider>
  );
}
